# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0002_auto_20170328_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='language',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='language_for', to='algo_app.Language'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_for',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='algo_solutions', to='algo_app.Algorithm'),
            preserve_default=False,
        ),
    ]
